id: I4CC9CAE1
legacy_id: P009438
ocr_import_info:
  bdrc_scan_id: W23437
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T03:50:54'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T01:04:17.136760+00:00'
last_modified: 2022-09-02 09:04:23.643649
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W23437
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW23437
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཞལ་འདོན་ཕྱོགས་བསྡེབས་བདེ་ནས་བདེ་བར་བགྲོད་པའི་ཐེམ་སྐས།
statistics:
  ocr_word_mean_confidence_index: 0.6325806432193325
  ocr_word_median_confidence_index: 0.6000000238418579
quality: null
bases:
  I1939:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1939
      total_pages: 552
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1939.txt
    statistics:
      ocr_word_median_confidence_index: 0.6000000238418579
      ocr_word_mean_confidence_index: 0.6325806432193325
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
